apiVersion: v1
data:
  KAFKA_SERVER: udaconnect-kafka-controller-3.udaconnect-kafka-controller-headless.default.svc.cluster.local:19092
  TOPIC_NAME: location-data
kind: ConfigMap
metadata:
  name: kafka-env
