name: build services

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - api
          - connections-api
          - frontend
          - location-ingester
          - location-service
          - persons-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build service
        run: |
          cd ${{ matrix.service }}
          docker build -t trucdp/${{ matrix.service }}:${{ github.sha }} .